services:
  postgres-account:
    image: postgres:latest
    container_name: account-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account
    ports:
      - "5432:5432"
    volumes:
      - postgres_account_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  postgres-auth:
    image: postgres:latest
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  account:
    build:
      context: ..
      dockerfile: services/account/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: ${BUILD_TIME:-unknown}
    container_name: account-service
    ports:
      - "9000:9000" # gRPC
    env_file:
      - ./account/.env
    depends_on:
      postgres-account:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  auth:
    build:
      context: ..
      dockerfile: services/auth/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: ${BUILD_TIME:-unknown}
    container_name: auth-service
    ports:
      - "9001:9001" # gRPC
    env_file:
      - ./auth/.env
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  gateway:
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: ${BUILD_TIME:-unknown}
    container_name: gateway-service
    ports:
      - "9002:9002" # gRPC
    env_file:
      - ./gateway/.env
    depends_on:
      - account
      - auth
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_account_data:
  postgres_auth_data:

networks:
  app-network:
    driver: bridge
