openapi: 3.0.1
info:
    title: Account Service
    version: 1.0.0
servers:
    - url: /api/v1
paths:
    /healthz:
        get:
            tags:
              - healthz
            summary: Health check endpoint
            description: Returns service health status
            operationId: healthz
            responses:
                200:
                    description: Service is healthy
                    content: {}
